### ISSUE TITLE
Error when installing pyinteraph2

### ISSUE THREAD

**Issue by antsasas** [ELELAB/pyinteraph2#101]
I get the following errors when installing the "setup.py" when following the conda installation guide.

clibinteract.c
libinteract/clibinteract.c(79): warning C4244: '=': conversion from 'double' to 'long', possible loss of data
libinteract/clibinteract.c(111): warning C4244: '=': conversion from 'double' to 'long', possible loss of data
libinteract/clibinteract.c(144): warning C4244: '=': conversion from 'double' to 'long', possible loss of data
libinteract/clibinteract.c(146): error C2057: expected constant expression
libinteract/clibinteract.c(146): error C2466: cannot allocate an array of constant size 0
libinteract/clibinteract.c(146): error C2133: 'sets_ends': unknown size
libinteract/clibinteract.c(147): error C2057: expected constant expression
libinteract/clibinteract.c(147): error C2466: cannot allocate an array of constant size 0
libinteract/clibinteract.c(147): error C2133: 'sets_starts': unknown size
libinteract/clibinteract.c(218): error C2057: expected constant expression
libinteract/clibinteract.c(218): error C2466: cannot allocate an array of constant size 0
libinteract/clibinteract.c(218): error C2133: 'sets_ends1': unknown size
libinteract/clibinteract.c(219): error C2057: expected constant expression
libinteract/clibinteract.c(219): error C2466: cannot allocate an array of constant size 0
libinteract/clibinteract.c(219): error C2133: 'sets_starts1': unknown size
libinteract/clibinteract.c(220): error C2057: expected constant expression
libinteract/clibinteract.c(220): error C2466: cannot allocate an array of constant size 0
libinteract/clibinteract.c(220): error C2133: 'sets_ends2': unknown size
libinteract/clibinteract.c(221): error C2057: expected constant expression
libinteract/clibinteract.c(221): error C2466: cannot allocate an array of constant size 0
libinteract/clibinteract.c(221): error C2133: 'sets_starts2': unknown size
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Is this a known issue with MVSC or something more related to my own end that I cannot figure out? I have searched and tried multiple solutions with the last error "failed exit status 2", but none of them have worked.

**Comment by skhatri007** [comment]
Resolved by reconfiguring the same. Please close the same .
