### ISSUE TITLE
typo in tutorials 

### ISSUE THREAD

**Issue by Comp-era** [ELELAB/pyinteraph2#102]
In the following tutorial , there is some typo,

#calculate interactions

#to calculate hbonds sc-sc

pyinteraph -s pdbmovie_1.pdb -t ../../../3.filt_trjs/traj_prot_dt1000.xtc -r pdbmovie_1.pdb **-f -**-hb-graph hb-graph.dat --ff-masses charmm27 -v --hb-ad-file hydrogen_bonds.ini

#to calculate hydrophobic interactions

pyinteraph -s pdbmovie_1.pdb -t ../../../3.filt_trjs/traj_prot_dt1000.xtc -r pdbmovie_1.pdb --hc-co 5 -f **--hc-graph hb-graph.dat** --ff-masses charmm27 -v --hc-residues ALA,VAL,LEU,ILE,PHE,PRO,MET,TRP

1- If -f flag is required for hbonds analysis 
2-output of -hc-graph is hb-graph.dat
Kindly clarify. As there may be wrong output generation during psn analysis .

**Comment by elenapapaleo** [comment]
fixed with https://github.com/ELELAB/pyinteraph2/pull/103
