### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by varundewaker** [ELELAB/pyinteraph2#50]
Dear ELELAB
I am facing a problem in installation of this package. Kindly help in troubleshooting. Following is the error message.
gcc: error: libinteract/innerloops.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.

**Comment by mtiberti** [comment]
Hi, sorry for the delayed response. It's a bit difficult to assist without having the full installation log, my best guess would be that you don't have the Cython package installed. Cython is necessary to generate `innerloops.c` during the installation process. Depending on what your setup is exactly there might be multiple ways to install it. I can help you better if you please include the full installation log and more details on your environment (e.g. if you're using an environment or not and what dependencies are installed)

**Comment by elenapapaleo** [comment]
Closing this issue since it has been inactive for a while. Can be reopened if needed
